### login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email" : "emcdil@email.com",
    "password": "password"
}


###upload image
POST http://localhost:3000/api/image/cloudinary-upload
Content-Type: multipart/form-data

{
    "file": "file"
}



###send email
POST http://localhost:3000/api/auth/sendmail
Content-Type: application/json

{
}



### signup
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "profile" : {
        "name" : "tadd3"
    },
    "username": "tdidcddcddd",
    "email" : "emcdddil@email.com",
    "password": "password"
}


### change email
POST http://localhost:3000/api/auth/emailchange
Content-Type: application/json

{
    "email" : "email@email.com",
    "new_email" : "email@email.com",
    "authorization" : "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6InRkaSIsInByb2ZpbGUiOiJ7IG5hbWU6ICd0YTMnIH0iLCJlbWFpbCI6ImVtYWlsQGVtYWlsLmNvbSIsImlhdCI6MTY5OTI1MTY1NiwiZXhwIjoxNjk5MjUyNTU2fQ.qrGHz9BSXIs-XzsblHeA6xdM876JPHsNJq2qLZN09Xc"
}


### change password
POST http://localhost:3000/api/auth/passwordchange
Content-Type: application/json

{
    "email" : "emcdil@email.com",
    "password" : "password",
    "new_password" : "password",
    "authorization" : "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6InRkaWRjZGNkZGQiLCJwcm9maWxlIjoieyBuYW1lOiAndGEzJyB9IiwiZW1haWwiOiJlbWNkaWxAZW1haWwuY29tIiwiaWF0IjoxNjk5MjUyODkxLCJleHAiOjE2OTkyNTM3OTF9.agJWwoNV7RF33TFC1zWr14pSmcLZfTR0oHT83CJ31TM"
}



### get all user
POST http://localhost:3000/api/user/getalluser
Content-Type: application/json

{
    "authorization" : "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ4ODlmMTRmYzQzZjk3NGJhYjJjMzkiLCJyb2xlcyI6IlVTRVIsSU5TVFJVQ1RPUixBRE1JTiIsInVzZXJuYW1lIjoidGRpZGNkY2RkZCIsInByb2ZpbGUiOiJ7IG5hbWU6ICd0YTMnIH0iLCJlbWFpbCI6ImVtY2RpbEBlbWFpbC5jb20iLCJpYXQiOjE3MDE5NTY4NDIsImV4cCI6MTcwMjAxNjg0Mn0.wWk7B3JcpmYgmqDxIwtSK-EGNHnw7x_ZmgDWZMRs4YE"
}



###change profile
POST http://localhost:3000/api/auth/passwordchange
Content-Type: application/json

{
    {
    "email" : "emcdil@email.com",
    "password" : "password",
    "profile" : "password",
    "authorization" : "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlcyI6IlVTRVIiLCJ1c2VybmFtZSI6InRkaWRjZGNkZGQiLCJwcm9maWxlIjoieyBuYW1lOiAndGEzJyB9IiwiZW1haWwiOiJlbWNkaWxAZW1haWwuY29tIiwiaWF0IjoxNjk5MjUzMzY0LCJleHAiOjE2OTkyNTQyNjR9.t4hoPbC9fkOtdldpHuHGKTUrxXuH5sEoGUHH8xq5RuE"
}
}


###create new course
POST http://localhost:3000/api/course/newcourse
Content-Type: application/json

{
    "email": "emcdil@email.com",
    "authorization" : "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ4ODlmMTRmYzQzZjk3NGJhYjJjMzkiLCJyb2xlcyI6IlVTRVIsSU5TVFJVQ1RPUixBRE1JTiIsInVzZXJuYW1lIjoidGRpZGNkY2RkZCIsInByb2ZpbGUiOiJ7IG5hbWU6ICd0YTMnIH0iLCJlbWFpbCI6ImVtY2RpbEBlbWFpbC5jb20iLCJpYXQiOjE3MDE5NTU0NDksImV4cCI6MTcwMjAxNTQ0OX0.M3jGaEx3-FbVZOUdD1_K2hLQ04uSti_1iz7yU7IOVOw",
    "title" : "tasddsds",
    "description": "tai",
    "categories": ["tai1", "tai2"],
    "tags": ["tai1", "tai2"],
    "price": 1000
}


### get user by id
POST http://localhost:3000/api/user/getuserbyid
Content-Type: application/json

{
    "userId" : "65449f40a8352632cba06e8e"
}

### get user by id
POST http://localhost:3000/api/user/disableuser
Content-Type: application/json

{
    "userid" : "654888f24fc43f974bab2c32",
    "email" : "emcdil@email.com",
    "authorization" : "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ4ODlmMTRmYzQzZjk3NGJhYjJjMzkiLCJyb2xlcyI6IlVTRVIsSU5TVFJVQ1RPUixBRE1JTiIsInVzZXJuYW1lIjoidGRpZGNkY2RkZCIsInByb2ZpbGUiOiJ7IG5hbWU6ICd0YTMnIH0iLCJlbWFpbCI6ImVtY2RpbEBlbWFpbC5jb20iLCJpYXQiOjE3MDAxMDI0MTQsImV4cCI6MTcwMDEwMzMxNH0.pALvO-6dq_pNglQ3AOAJ5VRgPwz0PaHaRTsy3xb5tXI"
}


### change course info
POST http://localhost:3000/api/course/changecourse
Content-Type: application/json

{
    "userid" : "654888f24fc43f974bab2c32",
    "email" : "emcdil@email.com",
    "authorization" : "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ4ODlmMTRmYzQzZjk3NGJhYjJjMzkiLCJyb2xlcyI6IlVTRVIsSU5TVFJVQ1RPUixBRE1JTiIsInVzZXJuYW1lIjoidGRpZGNkY2RkZCIsInByb2ZpbGUiOiJ7IG5hbWU6ICd0YTMnIH0iLCJlbWFpbCI6ImVtY2RpbEBlbWFpbC5jb20iLCJpYXQiOjE3MDAxMDQxMTUsImV4cCI6MTcwMDEwNTAxNX0.fiPuE_uAFseRxYRkck6TX_sugUvIyi02fpEdkKJ-Lek",
    "courseChanged" : {
        "_id" : "65556719a54c5bcbf51104e7",
        "title": "tai1"
    }
}


### get course by id
POST http://localhost:3000/api/course/getcoursebyid
Content-Type: application/json

{
    "courseId" : "6571433bdf10077c81fd2760"
}



### get all course

POST http://localhost:3000/api/course/getallcourse
Content-Type: application/json

{
}


### get all course admin
POST http://localhost:3000/api/course/getallcourseadmin
Content-Type: application/json

{
    "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ4ODlmMTRmYzQzZjk3NGJhYjJjMzkiLCJyb2xlcyI6IlVTRVIsSU5TVFJVQ1RPUixBRE1JTiIsInVzZXJuYW1lIjoidGRpZGNkY2RkZCIsInByb2ZpbGUiOiJ7IG5hbWU6ICd0YTMnIH0iLCJlbWFpbCI6ImVtY2RpbEBlbWFpbC5jb20iLCJpYXQiOjE3MDIwMDE2NjQsImV4cCI6MTcwMjA2MTY2NH0.EW0JuvHXDhGOMDqtT3wC_x7opCs9dFs6NfWW2iJnPN0"
}







### delete course
POST http://localhost:3000/api/course/deletecourse
Content-Type: application/json

{
    "courseId" : "6571c7a353adfa42c39c55ac",
    "email": "emil@email.com",
    "authorization" : "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ4ODlmMTRmYzQzZjk3NGJhYjJjMzkiLCJyb2xlcyI6IlVTRVIsSU5TVFJVQ1RPUixBRE1JTiIsInVzZXJuYW1lIjoidGRpZGNkY2RkZCIsInByb2ZpbGUiOiJ7IG5hbWU6ICd0YTMnIH0iLCJlbWFpbCI6ImVtY2RpbEBlbWFpbC5jb20iLCJpYXQiOjE3MDIyNTM0MzUsImV4cCI6MTcwMjMxMzQzNX0.yTimMWvL-323OoXmWamg7QnWoBUrAP6pFZFSbw8v0sg"
}



### get all course by author
POST http://localhost:3000/api/course/getallcoursebyauthor
Content-Type: application/json

{
    "email": "emil@email.com",
    "authorization" : "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ4ODhmMjRmYzQzZjk3NGJhYjJjMzIiLCJyb2xlcyI6IlVTRVIsSU5TVFJVQ1RPUiIsInVzZXJuYW1lIjoidGRpZGNkY2QiLCJwcm9maWxlIjoieyBuYW1lOiAndGEzJyB9IiwiZW1haWwiOiJlbWlsQGVtYWlsLmNvbSIsImlhdCI6MTcwMTY0OTczNiwiZXhwIjoxNzAxNjUwNjM2fQ.GO-s5vp6y7y1W31I92Ff_hjybQOexbVldTVsXtgdHlI",
    "author_id": "654888f24fc43f974bab2c32"
}


### get all course by tag
POST http://localhost:3000/api/course/getallcoursebytag
Content-Type: application/json

{
    "tags": ["tai1"]
}



### get all course by category
POST http://localhost:3000/api/course/getallcoursebycategory
Content-Type: application/json

{
    "categories": ["tai1"]
}



### search course by keyword
POST http://localhost:3000/api/course/searchcoursebykeyword
Content-Type: application/json

{
    "keyword": "a"
}



### get full course by id
POST http://localhost:3000/api/course/getfullcoursebyid
Content-Type: application/json

{
   "email": "emil@email.com",
  "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ4ODhmMjRmYzQzZjk3NGJhYjJjMzIiLCJyb2xlcyI6IlVTRVIsSU5TVFJVQ1RPUiIsInVzZXJuYW1lIjoidGRpZGNkY2QiLCJwcm9maWxlIjoieyBuYW1lOiAndGEzJyB9IiwiZW1haWwiOiJlbWlsQGVtYWlsLmNvbSIsImlhdCI6MTcwMTY1MDY5MCwiZXhwIjoxNzAxNjUxNTkwfQ.sagdNUEeGpQoMgP05O2hSjUJxnyl4nsJqYn1qBOLQoM",
    "courseId" : "656d1d805813d78553b4593c"
}



### create a new chapter
POST http://localhost:3000/api/chapter/newchapter
Content-Type: application/json

{
  "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ4ODlmMTRmYzQzZjk3NGJhYjJjMzkiLCJyb2xlcyI6IlVTRVIsSU5TVFJVQ1RPUixBRE1JTiIsInVzZXJuYW1lIjoidGRpZGNkY2RkZCIsInByb2ZpbGUiOiJ7IG5hbWU6ICd0YTMnIH0iLCJlbWFpbCI6ImVtY2RpbEBlbWFpbC5jb20iLCJpYXQiOjE3MDIwMDA4MzMsImV4cCI6MTcwMjA2MDgzM30.CHyaTtbLdrFiwVoEO_pXRdbJq9r9-PCsIgU4vd1-HDw",
  "title": "chapter1",
  "course_id":"6571433bdf10077c81fd2760",
  "order": 1
}



###change chapter
POST http://localhost:3000/api/chapter/changechapter
Content-Type: application/json

{
    "email": "emil@email.com",
  "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ4ODhmMjRmYzQzZjk3NGJhYjJjMzIiLCJyb2xlcyI6IlVTRVIsSU5TVFJVQ1RPUiIsInVzZXJuYW1lIjoidGRpZGNkY2QiLCJwcm9maWxlIjoieyBuYW1lOiAndGEzJyB9IiwiZW1haWwiOiJlbWlsQGVtYWlsLmNvbSIsImlhdCI6MTcwMTY1MjQxMiwiZXhwIjoxNzAxNjU4NDEyfQ.RUx_mixAR742U0jsQirsLiPgHzBtEFsDh-oS0SNoUGo",
  "chapter_id": "656d2953f50b344892f01c58",
  "course_id": "656d1d805813d78553b4593c",
  "change": {
    "title": "chapter10"
  }
}


###get all chapter with lesson
POST http://localhost:3000/api/chapter/getChapterWithLesson
Content-Type: application/json

{
  "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ4ODlmMTRmYzQzZjk3NGJhYjJjMzkiLCJyb2xlcyI6IlVTRVIsSU5TVFJVQ1RPUixBRE1JTiIsInVzZXJuYW1lIjoidGRpZGNkY2RkZCIsInByb2ZpbGUiOiJ7IG5hbWU6ICd0YTMnIH0iLCJlbWFpbCI6ImVtY2RpbEBlbWFpbC5jb20iLCJpYXQiOjE3MDE5OTg2OTcsImV4cCI6MTcwMjA1ODY5N30.gb9wl222zK96n6PdGm8UFuzLlCrK_QOWIhCOyTOA034",
  "course_id": "6571433bdf10077c81fd2760"
}


### get chapter by course
POST http://localhost:3000/api/chapter/getbycourse
Content-Type: application/json

{
    "course_id" : "656d1d805813d78553b4593c"
}



### get full chapter by course
POST http://localhost:3000/api/chapter/getbycourse
Content-Type: application/json

{
     "email": "emil@email.com",
  "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ4ODhmMjRmYzQzZjk3NGJhYjJjMzIiLCJyb2xlcyI6IlVTRVIsSU5TVFJVQ1RPUiIsInVzZXJuYW1lIjoidGRpZGNkY2QiLCJwcm9maWxlIjoieyBuYW1lOiAndGEzJyB9IiwiZW1haWwiOiJlbWlsQGVtYWlsLmNvbSIsImlhdCI6MTcwMTY1MjQxMiwiZXhwIjoxNzAxNjU4NDEyfQ.RUx_mixAR742U0jsQirsLiPgHzBtEFsDh-oS0SNoUGo",
    "course_id" : "656d1d805813d78553b4593c"
}



### create lesson
POST http://localhost:3000/api/lesson/newlesson
Content-Type: application/json

{
    "email": "emil@email.com",
  "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ4ODlmMTRmYzQzZjk3NGJhYjJjMzkiLCJyb2xlcyI6IlVTRVIsSU5TVFJVQ1RPUixBRE1JTiIsInVzZXJuYW1lIjoidGRpZGNkY2RkZCIsInByb2ZpbGUiOiJ7IG5hbWU6ICd0YTMnIH0iLCJlbWFpbCI6ImVtY2RpbEBlbWFpbC5jb20iLCJpYXQiOjE3MDE5OTg2MDcsImV4cCI6MTcwMjA1ODYwN30.CQZ5INklhrU1ceEAgPH6_v46T1ybhPWZShB_9UZuPFk",
    "chapter_id" : "657278d3e4c826285855fbb6",
    "title": "lesson2",
    "order": 2,
    "link": "lesson2"
}



### change lesson
POST http://localhost:3000/api/lesson/changelesson
Content-Type: application/json

{
     "email": "emil@email.com",
  "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ4ODhmMjRmYzQzZjk3NGJhYjJjMzIiLCJyb2xlcyI6IlVTRVIsSU5TVFJVQ1RPUiIsInVzZXJuYW1lIjoidGRpZGNkY2QiLCJwcm9maWxlIjoieyBuYW1lOiAndGEzJyB9IiwiZW1haWwiOiJlbWlsQGVtYWlsLmNvbSIsImlhdCI6MTcwMTY1ODU5MiwiZXhwIjoxNzAxNzE4NTkyfQ.4cCJ-R4rPvRHKE215aeNklkU6KE1emXH4YWm_FK3fiI",
    "course_id" : "656d1d805813d78553b4593c",
    "lesson_id" : "656d405cd806afa12d13eb52",
    "lesson_change": {
        "title": "lesson3"
    }

}





### get lesson by id
POST http://localhost:3000/api/lesson/getlessonbyid
Content-Type: application/json

{
     "email": "emil@email.com",
  "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ4ODhmMjRmYzQzZjk3NGJhYjJjMzIiLCJyb2xlcyI6IlVTRVIsSU5TVFJVQ1RPUiIsInVzZXJuYW1lIjoidGRpZGNkY2QiLCJwcm9maWxlIjoieyBuYW1lOiAndGEzJyB9IiwiZW1haWwiOiJlbWlsQGVtYWlsLmNvbSIsImlhdCI6MTcwMTY1ODU5MiwiZXhwIjoxNzAxNzE4NTkyfQ.4cCJ-R4rPvRHKE215aeNklkU6KE1emXH4YWm_FK3fiI",
    "course_id" : "656d1d805813d78553b4593c",
    "lesson_id" : "656d405cd806afa12d13eb52"
}



### get full lesson by chapter id
POST http://localhost:3000/api/lesson/getlessonbychapterid
Content-Type: application/json

{
     "email": "emil@email.com",
  "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ4ODhmMjRmYzQzZjk3NGJhYjJjMzIiLCJyb2xlcyI6IlVTRVIsSU5TVFJVQ1RPUiIsInVzZXJuYW1lIjoidGRpZGNkY2QiLCJwcm9maWxlIjoieyBuYW1lOiAndGEzJyB9IiwiZW1haWwiOiJlbWlsQGVtYWlsLmNvbSIsImlhdCI6MTcwMTY1ODU5MiwiZXhwIjoxNzAxNzE4NTkyfQ.4cCJ-R4rPvRHKE215aeNklkU6KE1emXH4YWm_FK3fiI",
    "course_id" : "656d1d805813d78553b4593c",
    "chapter" : "656d2953f50b344892f01c58"
}




###create payment
POST http://localhost:3000/api/payment/create
Content-Type: application/json

{
  "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ4ODlmMTRmYzQzZjk3NGJhYjJjMzkiLCJyb2xlcyI6IlVTRVIsSU5TVFJVQ1RPUixBRE1JTiIsInVzZXJuYW1lIjoidGRpZGNkY2RkZCIsInByb2ZpbGUiOiJ7IG5hbWU6ICd0YTMnIH0iLCJlbWFpbCI6ImVtY2RpbEBlbWFpbC5jb20iLCJpYXQiOjE3MDIwMDM1NjksImV4cCI6MTcwMjA2MzU2OX0.fxB-zveNhywmsv9FmKpuFtse6vz1IR90_vZrwXnKNz0",
  "course_id": "6571433bdf10077c81fd2760"
}



###delete payment
POST http://localhost:3000/api/payment/delete
Content-Type: application/json

{
  "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ4ODlmMTRmYzQzZjk3NGJhYjJjMzkiLCJyb2xlcyI6IlVTRVIsSU5TVFJVQ1RPUixBRE1JTiIsInVzZXJuYW1lIjoidGRpZGNkY2RkZCIsInByb2ZpbGUiOiJ7IG5hbWU6ICd0YTMnIH0iLCJlbWFpbCI6ImVtY2RpbEBlbWFpbC5jb20iLCJpYXQiOjE3MDIwMDM1NjksImV4cCI6MTcwMjA2MzU2OX0.fxB-zveNhywmsv9FmKpuFtse6vz1IR90_vZrwXnKNz0",
  "payment_id": "656d48fb35d72fb77697ab6e"
}



###get all payment
POST http://localhost:3000/api/payment/read
Content-Type: application/json

{
  "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ4ODlmMTRmYzQzZjk3NGJhYjJjMzkiLCJyb2xlcyI6IlVTRVIsSU5TVFJVQ1RPUixBRE1JTiIsInVzZXJuYW1lIjoidGRpZGNkY2RkZCIsInByb2ZpbGUiOiJ7IG5hbWU6ICd0YTMnIH0iLCJlbWFpbCI6ImVtY2RpbEBlbWFpbC5jb20iLCJpYXQiOjE3MDIwMDM1NjksImV4cCI6MTcwMjA2MzU2OX0.fxB-zveNhywmsv9FmKpuFtse6vz1IR90_vZrwXnKNz0"
}



###read review by id
POST http://localhost:3000/api/review/read
Content-Type: application/json

{
  "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ4ODlmMTRmYzQzZjk3NGJhYjJjMzkiLCJyb2xlcyI6IlVTRVIsSU5TVFJVQ1RPUixBRE1JTiIsInVzZXJuYW1lIjoidGRpZGNkY2RkZCIsInByb2ZpbGUiOiJ7IG5hbWU6ICd0YTMnIH0iLCJlbWFpbCI6ImVtY2RpbEBlbWFpbC5jb20iLCJpYXQiOjE3MDIwMDM1NjksImV4cCI6MTcwMjA2MzU2OX0.fxB-zveNhywmsv9FmKpuFtse6vz1IR90_vZrwXnKNz0",
  "course_id": "6571433bdf10077c81fd2760"
}


###create review
POST http://localhost:3000/api/review/create
Content-Type: application/json

{
  "authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NTQ4ODlmMTRmYzQzZjk3NGJhYjJjMzkiLCJyb2xlcyI6IlVTRVIsSU5TVFJVQ1RPUixBRE1JTiIsInVzZXJuYW1lIjoidGRpZGNkY2RkZCIsInByb2ZpbGUiOiJ7IG5hbWU6ICd0YTMnIH0iLCJlbWFpbCI6ImVtY2RpbEBlbWFpbC5jb20iLCJpYXQiOjE3MDIwMDM1NjksImV4cCI6MTcwMjA2MzU2OX0.fxB-zveNhywmsv9FmKpuFtse6vz1IR90_vZrwXnKNz0",
  "course_id": "6571433bdf10077c81fd2760",
  "rating": 4,
  "review_text": "hiện em mới bắt đầu học môn Cơ sở dữ liệu ở trường, nhưng mà thầy giảng lí thuyết nhiều quá, không biết khóa SQL Sever này có giống môn CSDL trên trường không ạ, em newbie mong mọi người đừng ném đá ạ, em cảm ơn"
}
